# Use the official Node.js image as the base image for building
FROM node:20-alpine AS builder

# Create and set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package.json package-lock.json ./

# Install dependencies
RUN npm install --prefer-offline --no-audit --progress=false --production=false

# Copy the rest of the application code
COPY . .

# Build the NestJS application
RUN npm run build

# Clean up node_modules and reinstall dependencies for production
RUN rm -rf node_modules && \
  npm install --prefer-offline --no-audit --progress=false --production=true

# Use the official Node.js image as the base image for running
FROM node:20-alpine

# Create and set the working directory
WORKDIR /app

# Copy the built application and production node_modules from the builder stage
COPY --from=builder /app .

# Expose the necessary port
EXPOSE 3000

# Command to run the application
CMD ["npm", "run", "start:prod"]
